### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by kvetinac97** [kvetinac97/Sudoku#2]
- [ ] předělat ukládání do souboru na
       originalnipole
      aktualnipole
       (to s těmi tahy je zbytečné, akorát je to matoucí)
 - [ ] když spustím hru, může se mi stát, že bude první pole 0;0 !!!
 - [ ] rekurze se při generování sudoku občas zacyklí, to se nesmí stát
 - [ ] nefunguje časomíra
